// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using Sw5e.Infrastructure.Persistence.Content;

#nullable disable

namespace Sw5e.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(Sw5eContentDbContext))]
    [Migration("20260902153600_RankProseWithFullTextSearch")]
    partial class RankProseWithFullTextSearch
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("content")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sw5e.Infrastructure.Persistence.Content.ContentDraftRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("BaseRevisionId")
                        .HasColumnType("bigint")
                        .HasColumnName("base_revision_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("body");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_type")
                        .UseCollation("C");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("ItemKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("item_key")
                        .UseCollation("C");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("name")
                        .UseCollation("C");

                    b.Property<Guid?>("ResolvesFlagId")
                        .HasColumnType("uuid")
                        .HasColumnName("resolves_flag_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_content_draft_updated");

                    b.HasIndex("ContentType", "ItemKey")
                        .IsUnique()
                        .HasDatabaseName("ix_content_draft_item");

                    b.ToTable("content_draft", "content", t =>
                        {
                            t.HasCheckConstraint("ck_content_draft_body_is_object", "jsonb_typeof(body) = 'object'");

                            t.HasCheckConstraint("ck_content_draft_key_slug", "item_key ~ '^[a-z0-9]+(-[a-z0-9]+)*$'");
                        });
                });

            modelBuilder.Entity("Sw5e.Infrastructure.Persistence.Content.ContentItemRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("body");

                    b.Property<string>("ContentSet")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_set")
                        .UseCollation("C");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_type")
                        .UseCollation("C");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Facets")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("facets");

                    b.Property<string>("HeadingTextLower")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("heading_text_lower")
                        .UseCollation("C");

                    b.Property<string>("ItemKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("item_key")
                        .UseCollation("C");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("name")
                        .UseCollation("C");

                    b.Property<string>("NameLower")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("name_lower")
                        .UseCollation("C");

                    b.Property<string>("SearchText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("search_text")
                        .UseCollation("C");

                    b.Property<string>("SearchTextLower")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("search_text_lower")
                        .UseCollation("C");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector")
                        .HasComputedColumnSql("setweight(to_tsvector('english', name_lower), 'A') ||\r\nsetweight(to_tsvector('english', heading_text_lower), 'B') ||\r\nsetweight(to_tsvector('english', search_text_lower), 'D')", true);

                    b.Property<string>("SourceKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source_key")
                        .UseCollation("C");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary")
                        .UseCollation("C");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("version")
                        .UseCollation("C");

                    b.HasKey("Id");

                    b.HasIndex("HeadingTextLower")
                        .HasDatabaseName("ix_content_item_heading_text_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("HeadingTextLower"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("HeadingTextLower"), new[] { "gin_trgm_ops" });

                    b.HasIndex("NameLower")
                        .HasDatabaseName("ix_content_item_name_lower_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("NameLower"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("NameLower"), new[] { "gin_trgm_ops" });

                    b.HasIndex("SearchTextLower")
                        .HasDatabaseName("ix_content_item_search_text_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchTextLower"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("SearchTextLower"), new[] { "gin_trgm_ops" });

                    b.HasIndex("ContentType", "ContentSet")
                        .HasDatabaseName("ix_content_item_type_content_set")
                        .HasFilter("content_set IS NOT NULL");

                    b.HasIndex("ContentType", "ItemKey")
                        .IsUnique()
                        .HasDatabaseName("ix_content_item_type_key");

                    b.HasIndex("ContentType", "SourceKey")
                        .HasDatabaseName("ix_content_item_type_source")
                        .HasFilter("source_key IS NOT NULL");

                    b.HasIndex("ContentType", "NameLower", "ItemKey")
                        .HasDatabaseName("ix_content_item_type_name");

                    b.ToTable("content_item", "content", t =>
                        {
                            t.HasCheckConstraint("ck_content_item_body_is_object", "jsonb_typeof(body) = 'object'");

                            t.HasCheckConstraint("ck_content_item_key_slug", "item_key ~ '^[a-z0-9]+(-[a-z0-9]+)*$'");
                        });
                });

            modelBuilder.Entity("Sw5e.Infrastructure.Persistence.Content.ContentReferenceRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("FromItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("from_item_id");

                    b.Property<string>("JsonPath")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("json_path")
                        .UseCollation("C");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<string>("Relation")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("relation")
                        .UseCollation("C");

                    b.Property<long?>("ResolvedItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("resolved_item_id");

                    b.Property<string>("TargetIdentifier")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("target_identifier")
                        .UseCollation("C");

                    b.Property<string>("TargetKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("target_kind")
                        .UseCollation("C");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("target_type")
                        .UseCollation("C");

                    b.HasKey("Id");

                    b.HasIndex("ResolvedItemId", "Relation")
                        .HasDatabaseName("ix_content_reference_resolved")
                        .HasFilter("resolved_item_id IS NOT NULL");

                    b.HasIndex("TargetType", "TargetIdentifier")
                        .HasDatabaseName("ix_content_reference_unresolved")
                        .HasFilter("resolved_item_id IS NULL");

                    b.HasIndex("FromItemId", "Relation", "JsonPath")
                        .IsUnique()
                        .HasDatabaseName("ix_content_reference_from_path");

                    b.ToTable("content_reference", "content");
                });

            modelBuilder.Entity("Sw5e.Infrastructure.Persistence.Content.ContentRevisionRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("action")
                        .UseCollation("C");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("body");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_type")
                        .UseCollation("C");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ItemKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("item_key")
                        .UseCollation("C");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("name")
                        .UseCollation("C");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason")
                        .UseCollation("C");

                    b.Property<long?>("RevertedFromId")
                        .HasColumnType("bigint")
                        .HasColumnName("reverted_from_id");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("version")
                        .UseCollation("C");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId", "CreatedAt")
                        .HasDatabaseName("ix_content_revision_actor")
                        .HasFilter("actor_user_id IS NOT NULL");

                    b.HasIndex("ContentType", "ItemKey", "CreatedAt")
                        .HasDatabaseName("ix_content_revision_item_time");

                    b.HasIndex("ContentType", "ItemKey", "Number")
                        .IsUnique()
                        .HasDatabaseName("ix_content_revision_item_number");

                    b.ToTable("content_revision", "content", t =>
                        {
                            t.HasCheckConstraint("ck_content_revision_body_is_object", "jsonb_typeof(body) = 'object'");

                            t.HasCheckConstraint("ck_content_revision_key_slug", "item_key ~ '^[a-z0-9]+(-[a-z0-9]+)*$'");

                            t.HasCheckConstraint("ck_content_revision_number_positive", "number >= 1");
                        });
                });

            modelBuilder.Entity("Sw5e.Infrastructure.Persistence.Content.ContentTypeRow", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key")
                        .UseCollation("C");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("display_name")
                        .UseCollation("C");

                    b.Property<string>("PluralName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("plural_name")
                        .UseCollation("C");

                    b.Property<string>("RouteSegment")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("route_segment")
                        .UseCollation("C");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Key");

                    b.ToTable("content_type", "content");

                    b.HasData(
                        new
                        {
                            Key = "source",
                            DisplayName = "Source",
                            PluralName = "Sources",
                            RouteSegment = "sources",
                            SortOrder = 0
                        },
                        new
                        {
                            Key = "species",
                            DisplayName = "Species",
                            PluralName = "Species",
                            RouteSegment = "species",
                            SortOrder = 1
                        },
                        new
                        {
                            Key = "background",
                            DisplayName = "Background",
                            PluralName = "Backgrounds",
                            RouteSegment = "backgrounds",
                            SortOrder = 2
                        },
                        new
                        {
                            Key = "class",
                            DisplayName = "Class",
                            PluralName = "Classes",
                            RouteSegment = "classes",
                            SortOrder = 3
                        },
                        new
                        {
                            Key = "class-improvement",
                            DisplayName = "Class improvement",
                            PluralName = "Class improvements",
                            RouteSegment = "class-improvements",
                            SortOrder = 4
                        },
                        new
                        {
                            Key = "archetype",
                            DisplayName = "Archetype",
                            PluralName = "Archetypes",
                            RouteSegment = "archetypes",
                            SortOrder = 5
                        },
                        new
                        {
                            Key = "feature",
                            DisplayName = "Feature",
                            PluralName = "Features",
                            RouteSegment = "features",
                            SortOrder = 6
                        },
                        new
                        {
                            Key = "feat",
                            DisplayName = "Feat",
                            PluralName = "Feats",
                            RouteSegment = "feats",
                            SortOrder = 7
                        },
                        new
                        {
                            Key = "power",
                            DisplayName = "Power",
                            PluralName = "Powers",
                            RouteSegment = "powers",
                            SortOrder = 8
                        },
                        new
                        {
                            Key = "maneuver",
                            DisplayName = "Maneuver",
                            PluralName = "Maneuvers",
                            RouteSegment = "maneuvers",
                            SortOrder = 9
                        },
                        new
                        {
                            Key = "fighting-style",
                            DisplayName = "Fighting Style",
                            PluralName = "Fighting Styles",
                            RouteSegment = "fighting-styles",
                            SortOrder = 10
                        },
                        new
                        {
                            Key = "fighting-mastery",
                            DisplayName = "Fighting Mastery",
                            PluralName = "Fighting Masteries",
                            RouteSegment = "fighting-masteries",
                            SortOrder = 11
                        },
                        new
                        {
                            Key = "lightsaber-form",
                            DisplayName = "Lightsaber Form",
                            PluralName = "Lightsaber Forms",
                            RouteSegment = "lightsaber-forms",
                            SortOrder = 12
                        },
                        new
                        {
                            Key = "weapon-focus",
                            DisplayName = "Weapon Focus",
                            PluralName = "Weapon Focuses",
                            RouteSegment = "weapon-focuses",
                            SortOrder = 13
                        },
                        new
                        {
                            Key = "weapon-supremacy",
                            DisplayName = "Weapon Supremacy",
                            PluralName = "Weapon Supremacies",
                            RouteSegment = "weapon-supremacies",
                            SortOrder = 14
                        },
                        new
                        {
                            Key = "equipment",
                            DisplayName = "Equipment",
                            PluralName = "Equipment",
                            RouteSegment = "equipment",
                            SortOrder = 15
                        },
                        new
                        {
                            Key = "enhanced-item",
                            DisplayName = "Enhanced item",
                            PluralName = "Enhanced items",
                            RouteSegment = "enhanced-items",
                            SortOrder = 16
                        },
                        new
                        {
                            Key = "weapon-property",
                            DisplayName = "Weapon property",
                            PluralName = "Weapon properties",
                            RouteSegment = "weapon-properties",
                            SortOrder = 17
                        },
                        new
                        {
                            Key = "armor-property",
                            DisplayName = "Armor property",
                            PluralName = "Armor properties",
                            RouteSegment = "armor-properties",
                            SortOrder = 18
                        },
                        new
                        {
                            Key = "monster",
                            DisplayName = "Monster",
                            PluralName = "Monsters",
                            RouteSegment = "monsters",
                            SortOrder = 19
                        },
                        new
                        {
                            Key = "starship-base-size",
                            DisplayName = "Starship Base Size",
                            PluralName = "Starship Base Sizes",
                            RouteSegment = "starship-base-sizes",
                            SortOrder = 20
                        },
                        new
                        {
                            Key = "starship-deployment",
                            DisplayName = "Starship Deployment",
                            PluralName = "Starship Deployments",
                            RouteSegment = "starship-deployments",
                            SortOrder = 21
                        },
                        new
                        {
                            Key = "starship-equipment",
                            DisplayName = "Starship Equipment",
                            PluralName = "Starship Equipment",
                            RouteSegment = "starship-equipment",
                            SortOrder = 22
                        },
                        new
                        {
                            Key = "starship-modification",
                            DisplayName = "Starship Modification",
                            PluralName = "Starship Modifications",
                            RouteSegment = "starship-modifications",
                            SortOrder = 23
                        },
                        new
                        {
                            Key = "starship-venture",
                            DisplayName = "Starship Venture",
                            PluralName = "Starship Ventures",
                            RouteSegment = "starship-ventures",
                            SortOrder = 24
                        },
                        new
                        {
                            Key = "starship-rule",
                            DisplayName = "Starship Rule",
                            PluralName = "Starship Rules",
                            RouteSegment = "starship-rules",
                            SortOrder = 25
                        },
                        new
                        {
                            Key = "rule",
                            DisplayName = "Rule",
                            PluralName = "Rules",
                            RouteSegment = "rules",
                            SortOrder = 26
                        },
                        new
                        {
                            Key = "reference-table",
                            DisplayName = "Reference table",
                            PluralName = "Reference tables",
                            RouteSegment = "reference-tables",
                            SortOrder = 27
                        },
                        new
                        {
                            Key = "credit-category",
                            DisplayName = "Credit category",
                            PluralName = "Credit categories",
                            RouteSegment = "credit-categories",
                            SortOrder = 28
                        },
                        new
                        {
                            Key = "credit",
                            DisplayName = "Credit",
                            PluralName = "Credits",
                            RouteSegment = "credits",
                            SortOrder = 29
                        },
                        new
                        {
                            Key = "asset-credit",
                            DisplayName = "Asset credit",
                            PluralName = "Asset credits",
                            RouteSegment = "asset-credits",
                            SortOrder = 30
                        });
                });

            modelBuilder.Entity("Sw5e.Infrastructure.Persistence.Content.ContentDraftRow", b =>
                {
                    b.HasOne("Sw5e.Infrastructure.Persistence.Content.ContentTypeRow", null)
                        .WithMany()
                        .HasForeignKey("ContentType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sw5e.Infrastructure.Persistence.Content.ContentItemRow", b =>
                {
                    b.HasOne("Sw5e.Infrastructure.Persistence.Content.ContentTypeRow", null)
                        .WithMany()
                        .HasForeignKey("ContentType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sw5e.Infrastructure.Persistence.Content.ContentReferenceRow", b =>
                {
                    b.HasOne("Sw5e.Infrastructure.Persistence.Content.ContentItemRow", "FromItem")
                        .WithMany("References")
                        .HasForeignKey("FromItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sw5e.Infrastructure.Persistence.Content.ContentItemRow", "ResolvedItem")
                        .WithMany()
                        .HasForeignKey("ResolvedItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FromItem");

                    b.Navigation("ResolvedItem");
                });

            modelBuilder.Entity("Sw5e.Infrastructure.Persistence.Content.ContentRevisionRow", b =>
                {
                    b.HasOne("Sw5e.Infrastructure.Persistence.Content.ContentTypeRow", null)
                        .WithMany()
                        .HasForeignKey("ContentType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sw5e.Infrastructure.Persistence.Content.ContentItemRow", b =>
                {
                    b.Navigation("References");
                });
#pragma warning restore 612, 618
        }
    }
}
