// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sw5e.Infrastructure.Persistence.Content;

#nullable disable

namespace Sw5e.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(Sw5eContentDbContext))]
    partial class Sw5eContentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("content")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sw5e.Infrastructure.Persistence.Content.ContentItemRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("body");

                    b.Property<string>("ContentSet")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_set")
                        .UseCollation("C");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_type")
                        .UseCollation("C");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Facets")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("facets");

                    b.Property<string>("ItemKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("item_key")
                        .UseCollation("C");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("name")
                        .UseCollation("C");

                    b.Property<string>("NameLower")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("name_lower")
                        .UseCollation("C");

                    b.Property<string>("SearchText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("search_text")
                        .UseCollation("C");

                    b.Property<string>("SearchTextLower")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("search_text_lower")
                        .UseCollation("C");

                    b.Property<string>("SourceKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source_key")
                        .UseCollation("C");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary")
                        .UseCollation("C");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("version")
                        .UseCollation("C");

                    b.HasKey("Id");

                    b.HasIndex("NameLower")
                        .HasDatabaseName("ix_content_item_name_lower_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("NameLower"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("NameLower"), new[] { "gin_trgm_ops" });

                    b.HasIndex("SearchTextLower")
                        .HasDatabaseName("ix_content_item_search_text_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchTextLower"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("SearchTextLower"), new[] { "gin_trgm_ops" });

                    b.HasIndex("ContentType", "ContentSet")
                        .HasDatabaseName("ix_content_item_type_content_set")
                        .HasFilter("content_set IS NOT NULL");

                    b.HasIndex("ContentType", "ItemKey")
                        .IsUnique()
                        .HasDatabaseName("ix_content_item_type_key");

                    b.HasIndex("ContentType", "SourceKey")
                        .HasDatabaseName("ix_content_item_type_source")
                        .HasFilter("source_key IS NOT NULL");

                    b.HasIndex("ContentType", "NameLower", "ItemKey")
                        .HasDatabaseName("ix_content_item_type_name");

                    b.ToTable("content_item", "content", t =>
                        {
                            t.HasCheckConstraint("ck_content_item_body_is_object", "jsonb_typeof(body) = 'object'");

                            t.HasCheckConstraint("ck_content_item_key_slug", "item_key ~ '^[a-z0-9]+(-[a-z0-9]+)*$'");
                        });
                });

            modelBuilder.Entity("Sw5e.Infrastructure.Persistence.Content.ContentReferenceRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("FromItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("from_item_id");

                    b.Property<string>("JsonPath")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("json_path")
                        .UseCollation("C");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<string>("Relation")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("relation")
                        .UseCollation("C");

                    b.Property<long?>("ResolvedItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("resolved_item_id");

                    b.Property<string>("TargetIdentifier")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("target_identifier")
                        .UseCollation("C");

                    b.Property<string>("TargetKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("target_kind")
                        .UseCollation("C");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("target_type")
                        .UseCollation("C");

                    b.HasKey("Id");

                    b.HasIndex("ResolvedItemId", "Relation")
                        .HasDatabaseName("ix_content_reference_resolved")
                        .HasFilter("resolved_item_id IS NOT NULL");

                    b.HasIndex("TargetType", "TargetIdentifier")
                        .HasDatabaseName("ix_content_reference_unresolved")
                        .HasFilter("resolved_item_id IS NULL");

                    b.HasIndex("FromItemId", "Relation", "JsonPath")
                        .IsUnique()
                        .HasDatabaseName("ix_content_reference_from_path");

                    b.ToTable("content_reference", "content");
                });

            modelBuilder.Entity("Sw5e.Infrastructure.Persistence.Content.ContentTypeRow", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key")
                        .UseCollation("C");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("display_name")
                        .UseCollation("C");

                    b.Property<string>("PluralName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("plural_name")
                        .UseCollation("C");

                    b.Property<string>("RouteSegment")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("route_segment")
                        .UseCollation("C");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Key");

                    b.ToTable("content_type", "content");

                    b.HasData(
                        new
                        {
                            Key = "source",
                            DisplayName = "Source",
                            PluralName = "Sources",
                            RouteSegment = "sources",
                            SortOrder = 0
                        },
                        new
                        {
                            Key = "species",
                            DisplayName = "Species",
                            PluralName = "Species",
                            RouteSegment = "species",
                            SortOrder = 1
                        },
                        new
                        {
                            Key = "background",
                            DisplayName = "Background",
                            PluralName = "Backgrounds",
                            RouteSegment = "backgrounds",
                            SortOrder = 2
                        },
                        new
                        {
                            Key = "archetype",
                            DisplayName = "Archetype",
                            PluralName = "Archetypes",
                            RouteSegment = "archetypes",
                            SortOrder = 3
                        },
                        new
                        {
                            Key = "feature",
                            DisplayName = "Feature",
                            PluralName = "Features",
                            RouteSegment = "features",
                            SortOrder = 4
                        },
                        new
                        {
                            Key = "feat",
                            DisplayName = "Feat",
                            PluralName = "Feats",
                            RouteSegment = "feats",
                            SortOrder = 5
                        },
                        new
                        {
                            Key = "power",
                            DisplayName = "Power",
                            PluralName = "Powers",
                            RouteSegment = "powers",
                            SortOrder = 6
                        },
                        new
                        {
                            Key = "equipment",
                            DisplayName = "Equipment",
                            PluralName = "Equipment",
                            RouteSegment = "equipment",
                            SortOrder = 7
                        },
                        new
                        {
                            Key = "monster",
                            DisplayName = "Monster",
                            PluralName = "Monsters",
                            RouteSegment = "monsters",
                            SortOrder = 8
                        });
                });

            modelBuilder.Entity("Sw5e.Infrastructure.Persistence.Content.ContentItemRow", b =>
                {
                    b.HasOne("Sw5e.Infrastructure.Persistence.Content.ContentTypeRow", null)
                        .WithMany()
                        .HasForeignKey("ContentType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sw5e.Infrastructure.Persistence.Content.ContentReferenceRow", b =>
                {
                    b.HasOne("Sw5e.Infrastructure.Persistence.Content.ContentItemRow", "FromItem")
                        .WithMany("References")
                        .HasForeignKey("FromItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sw5e.Infrastructure.Persistence.Content.ContentItemRow", "ResolvedItem")
                        .WithMany()
                        .HasForeignKey("ResolvedItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FromItem");

                    b.Navigation("ResolvedItem");
                });

            modelBuilder.Entity("Sw5e.Infrastructure.Persistence.Content.ContentItemRow", b =>
                {
                    b.Navigation("References");
                });
#pragma warning restore 612, 618
        }
    }
}
