using System.Net;
using System.Net.Http.Json;
using Shouldly;

namespace Sw5e.Api.Tests.Integration.Accounts;

/// <summary>
/// Signing in with a code emailed to the account's address.
/// </summary>
/// <remarks>
/// <para>
/// The positive case here is one test. The other twenty are the negatives, and
/// that ratio is deliberate: a one-time code is only a credential at all
/// because of the things it refuses to do. A suite that proved a correct code
/// signs somebody in would pass against an endpoint that accepted every code,
/// accepted the same code forever, accepted a code for somebody else's address,
/// and mailed a stranger's inbox on demand.
/// </para>
/// <para>
/// Every code used below is read out of the captured message rather than
/// generated by the test, for the same reason the verification-token tests read
/// theirs out of the emailed link: a test that mints its own credential is
/// asserting that the server accepts credentials the test made up.
/// </para>
/// </remarks>
[Collection(AccountTestCollection.Name)]
public sealed class EmailCodeSignInTests(PostgresFixture postgres) : IAsyncLifetime
{
    private AccountApiFactory _factory = null!;

    public Task InitializeAsync()
    {
        _factory = new AccountApiFactory(postgres);
        return Task.CompletedTask;
    }

    public async Task DisposeAsync() => await _factory.DisposeAsync();

    [Fact]
    public async Task ACodeSentToAVerifiedAccountSignsItIn()
    {
        var client = _factory.CreateBrowserClient();
        var account = await EstablishAsync(client, "code-happy");

        await client.PostAsync("/api/auth/logout", content: null);

        var fresh = _factory.CreateBrowserClient();

        var requested = await RequestCodeAsync(fresh, account.EmailAddress);
        requested.StatusCode.ShouldBe(HttpStatusCode.Accepted);

        var verify = await VerifyCodeAsync(
            fresh, account.EmailAddress, _factory.Email.LatestSignInCode(account.EmailAddress));

        verify.StatusCode.ShouldBe(HttpStatusCode.OK);

        var body = await verify.ReadJsonAsync();
        body.GetProperty("status").GetString().ShouldBe("authenticated");
        body.GetProperty("user").GetProperty("email").GetString().ShouldBe(account.EmailAddress);

        // Claiming to be signed in and being signed in are different things,
        // and only the second one is worth testing.
        var me = await fresh.GetAsync("/api/auth/me");
        me.StatusCode.ShouldBe(HttpStatusCode.OK);

        // The session records that it was established weakly. Everything the
        // elevated-role tests assert rests on this value being written here.
        var profile = await me.ReadJsonAsync();
        profile.GetProperty("authenticationMethod").GetString().ShouldBe("email");
        profile.GetProperty("strongAuthentication").GetBoolean().ShouldBeFalse();
    }

    [Fact]
    public async Task ACodeThatHasAlreadyBeenUsedIsRefused()
    {
        var client = _factory.CreateBrowserClient();
        var account = await EstablishAsync(client, "code-reuse");
        await client.PostAsync("/api/auth/logout", content: null);

        var first = _factory.CreateBrowserClient();
        await RequestCodeAsync(first, account.EmailAddress);

        var code = _factory.Email.LatestSignInCode(account.EmailAddress);

        (await VerifyCodeAsync(first, account.EmailAddress, code))
            .StatusCode.ShouldBe(HttpStatusCode.OK);

        // A second browser, so this cannot pass or fail because of anything the
        // first one is holding. The code itself must be dead.
        var second = _factory.CreateBrowserClient();

        (await VerifyCodeAsync(second, account.EmailAddress, code))
            .StatusCode.ShouldBe(HttpStatusCode.Unauthorized);

        (await second.GetAsync("/api/auth/me")).StatusCode.ShouldBe(HttpStatusCode.Unauthorized);
    }

    [Fact]
    public async Task ACodeThatHasExpiredIsRefused()
    {
        var client = _factory.CreateBrowserClient();
        var account = await EstablishAsync(client, "code-expiry");
        await client.PostAsync("/api/auth/logout", content: null);

        var fresh = _factory.CreateBrowserClient();
        await RequestCodeAsync(fresh, account.EmailAddress);

        var code = _factory.Email.LatestSignInCode(account.EmailAddress);

        // Past the ten-minute lifetime and not far past it. Advancing by a day
        // would pass against a server whose expiry check was an hour out.
        _factory.Clock.Advance(TimeSpan.FromMinutes(11));

        (await VerifyCodeAsync(fresh, account.EmailAddress, code))
            .StatusCode.ShouldBe(HttpStatusCode.Unauthorized);

        (await fresh.GetAsync("/api/auth/me")).StatusCode.ShouldBe(HttpStatusCode.Unauthorized);
    }

    [Fact]
    public async Task ACodeIsStillGoodJustBeforeItExpires()
    {
        // The control for the test above. Without it, an implementation that
        // expired every code immediately would pass the expiry test and fail
        // nothing else in this file except the happy path — which runs fast
        // enough to hide it.
        var client = _factory.CreateBrowserClient();
        var account = await EstablishAsync(client, "code-not-yet-expired");
        await client.PostAsync("/api/auth/logout", content: null);

        var fresh = _factory.CreateBrowserClient();
        await RequestCodeAsync(fresh, account.EmailAddress);

        var code = _factory.Email.LatestSignInCode(account.EmailAddress);

        _factory.Clock.Advance(TimeSpan.FromMinutes(9));

        (await VerifyCodeAsync(fresh, account.EmailAddress, code))
            .StatusCode.ShouldBe(HttpStatusCode.OK);
    }

    [Fact]
    public async Task ACodeIssuedForOneAddressDoesNotWorkForAnother()
    {
        var client = _factory.CreateBrowserClient();
        var victim = await EstablishAsync(client, "code-victim");
        await client.PostAsync("/api/auth/logout", content: null);

        var attackerClient = _factory.CreateBrowserClient();
        var attacker = await EstablishAsync(attackerClient, "code-attacker");
        await attackerClient.PostAsync("/api/auth/logout", content: null);

        // The attacker asks for a code for their own address and receives it
        // legitimately, then tries to redeem it against somebody else's.
        var fresh = _factory.CreateBrowserClient();
        await RequestCodeAsync(fresh, attacker.EmailAddress);

        var attackerCode = _factory.Email.LatestSignInCode(attacker.EmailAddress);

        await RequestCodeAsync(fresh, victim.EmailAddress);

        (await VerifyCodeAsync(fresh, victim.EmailAddress, attackerCode))
            .StatusCode.ShouldBe(HttpStatusCode.Unauthorized);

        (await fresh.GetAsync("/api/auth/me")).StatusCode.ShouldBe(HttpStatusCode.Unauthorized);
    }

    [Fact]
    public async Task ACodeDiesAfterItsAttemptsAreSpent()
    {
        var client = _factory.CreateBrowserClient();
        var account = await EstablishAsync(client, "code-attempts");
        await client.PostAsync("/api/auth/logout", content: null);

        var fresh = _factory.CreateBrowserClient();
        await RequestCodeAsync(fresh, account.EmailAddress);

        var code = _factory.Email.LatestSignInCode(account.EmailAddress);
        var wrong = Wrong(code);

        for (var attempt = 0; attempt < 5; attempt++)
        {
            (await VerifyCodeAsync(fresh, account.EmailAddress, wrong))
                .StatusCode.ShouldBe(HttpStatusCode.Unauthorized);
        }

        // The correct code, after the budget is gone. This is the assertion
        // that distinguishes a real attempt limit from a counter nothing reads.
        (await VerifyCodeAsync(fresh, account.EmailAddress, code))
            .StatusCode.ShouldBe(HttpStatusCode.Unauthorized);

        (await fresh.GetAsync("/api/auth/me")).StatusCode.ShouldBe(HttpStatusCode.Unauthorized);
    }

    [Fact]
    public async Task AWrongCodeInsideTheBudgetDoesNotStopTheRightOneWorking()
    {
        // The control for the test above: an attempt limit that killed the code
        // on the first wrong guess would be indistinguishable there, and would
        // be a miserable experience for anybody who mistypes.
        var client = _factory.CreateBrowserClient();
        var account = await EstablishAsync(client, "code-one-slip");
        await client.PostAsync("/api/auth/logout", content: null);

        var fresh = _factory.CreateBrowserClient();
        await RequestCodeAsync(fresh, account.EmailAddress);

        var code = _factory.Email.LatestSignInCode(account.EmailAddress);

        (await VerifyCodeAsync(fresh, account.EmailAddress, Wrong(code)))
            .StatusCode.ShouldBe(HttpStatusCode.Unauthorized);

        (await VerifyCodeAsync(fresh, account.EmailAddress, code))
            .StatusCode.ShouldBe(HttpStatusCode.OK);
    }

    [Fact]
    public async Task AnUnknownAddressIsAnsweredIdenticallyToAKnownOne()
    {
        var client = _factory.CreateBrowserClient();
        var account = await EstablishAsync(client, "code-enumeration");
        await client.PostAsync("/api/auth/logout", content: null);

        var stranger = AccountFlow.NewAddress("code-nobody");

        var known = _factory.CreateBrowserClient();
        var unknown = _factory.CreateBrowserClient();

        var knownResponse = await RequestCodeAsync(known, account.EmailAddress);
        var unknownResponse = await RequestCodeAsync(unknown, stranger);

        knownResponse.StatusCode.ShouldBe(unknownResponse.StatusCode);
        knownResponse.StatusCode.ShouldBe(HttpStatusCode.Accepted);

        // Byte for byte. A difference of one word in the message would be
        // enough to tell a stranger whether somebody has an account here.
        var knownBody = await knownResponse.Content.ReadAsStringAsync();
        var unknownBody = await unknownResponse.Content.ReadAsStringAsync();

        knownBody.ShouldBe(unknownBody);

        // And the mechanism that keeps the two branches doing the same work: a
        // message goes out either way. If this ever stops being true the two
        // branches stop taking the same time, and the response time becomes the
        // oracle the body is not.
        _factory.Email.CountOf(AccountMessageKind.SignInCode, account.EmailAddress).ShouldBe(1);
        _factory.Email.CountOf(AccountMessageKind.UnknownAddressNotice, stranger).ShouldBe(1);

        // The unregistered address is told nothing that could sign anybody in.
        _factory.Email.CountOf(AccountMessageKind.SignInCode, stranger).ShouldBe(0);
    }

    [Fact]
    public async Task AnUnverifiedAccountCannotBeEnteredWithACode()
    {
        // Registering somebody else's address and then signing in with a code
        // sent to it would be a complete bypass of email verification. The
        // account exists at this point; it has simply never proved it controls
        // the address.
        var client = _factory.CreateBrowserClient();
        var account = AccountFlow.For(client, "code-unverified");

        await account.RegisterAsync();
        await RequestCodeAsync(client, account.EmailAddress);

        var code = _factory.Email.LatestSignInCode(account.EmailAddress);

        (await VerifyCodeAsync(client, account.EmailAddress, code))
            .StatusCode.ShouldBe(HttpStatusCode.Unauthorized);

        (await client.GetAsync("/api/auth/me")).StatusCode.ShouldBe(HttpStatusCode.Unauthorized);
    }

    [Fact]
    public async Task AnAccountWithAnAuthenticatorAppStillHasToUseIt()
    {
        var client = _factory.CreateBrowserClient();
        var account = await EstablishAsync(client, "code-mfa");

        var uri = await EnableTwoFactorAsync(client);

        await client.PostAsync("/api/auth/logout", content: null);

        var fresh = _factory.CreateBrowserClient();
        await RequestCodeAsync(fresh, account.EmailAddress);

        var verify = await VerifyCodeAsync(
            fresh, account.EmailAddress, _factory.Email.LatestSignInCode(account.EmailAddress));

        verify.StatusCode.ShouldBe(HttpStatusCode.OK);

        var body = await verify.ReadJsonAsync();
        body.GetProperty("status").GetString().ShouldBe("mfaRequired");

        // Reporting mfaRequired and issuing a session anyway would look
        // identical from the response alone. This is the check that the second
        // factor is load-bearing on this path too.
        (await fresh.GetAsync("/api/auth/me")).StatusCode.ShouldBe(HttpStatusCode.Unauthorized);

        var code = TimeBasedOneTimePassword.Generate(TimeBasedOneTimePassword.SecretFrom(uri));

        var totp = await fresh.PostAsJsonAsync("/api/auth/mfa/totp/verify", new { code });
        totp.StatusCode.ShouldBe(HttpStatusCode.OK);

        (await totp.ReadJsonAsync()).GetProperty("status").GetString().ShouldBe("authenticated");

        // Having produced an authenticator code, the session is now a strong
        // one even though it began with an emailed code.
        var me = await fresh.GetAsync("/api/auth/me");
        me.StatusCode.ShouldBe(HttpStatusCode.OK);

        (await me.ReadJsonAsync()).GetProperty("strongAuthentication").GetBoolean().ShouldBeTrue();
    }

    [Fact]
    public async Task AnAddressCannotBeMailedRepeatedly()
    {
        var client = _factory.CreateBrowserClient();
        var account = await EstablishAsync(client, "code-address-budget");
        await client.PostAsync("/api/auth/logout", content: null);

        var fresh = _factory.CreateBrowserClient();

        // Six requests, spaced past the resend cooldown so that it is the
        // per-address budget of three doing the refusing and not the cooldown.
        for (var request = 0; request < 6; request++)
        {
            var response = await RequestCodeAsync(fresh, account.EmailAddress);

            // Every one of them is accepted, including the ones that send
            // nothing. Answering 429 to the fourth would confirm to an
            // unauthenticated caller that this address had recently been asked
            // for — which is a smaller leak than account existence and is still
            // a leak.
            response.StatusCode.ShouldBe(HttpStatusCode.Accepted);

            _factory.Clock.Advance(TimeSpan.FromSeconds(90));
        }

        // Three inside the fifteen-minute window, and no more. This is the
        // limit that stops the sign-in form being a mail cannon anybody can
        // point at a stranger's inbox.
        _factory.Email
            .CountOf(AccountMessageKind.SignInCode, account.EmailAddress)
            .ShouldBe(3);
    }

    [Fact]
    public async Task AResendIsRefusedInsideTheCooldown()
    {
        var client = _factory.CreateBrowserClient();
        var account = await EstablishAsync(client, "code-cooldown");
        await client.PostAsync("/api/auth/logout", content: null);

        var fresh = _factory.CreateBrowserClient();

        await RequestCodeAsync(fresh, account.EmailAddress);
        await RequestCodeAsync(fresh, account.EmailAddress);

        // Two requests, one message: a held-down resend button delivers once.
        _factory.Email
            .CountOf(AccountMessageKind.SignInCode, account.EmailAddress)
            .ShouldBe(1);

        _factory.Clock.Advance(TimeSpan.FromSeconds(61));

        await RequestCodeAsync(fresh, account.EmailAddress);

        // And once the cooldown has passed, a resend actually resends. Without
        // this half, a cooldown that never expired would pass the assertion
        // above and leave anybody whose first message went astray stuck.
        _factory.Email
            .CountOf(AccountMessageKind.SignInCode, account.EmailAddress)
            .ShouldBe(2);
    }

    [Fact]
    public async Task ANewerCodeDoesNotResurrectAnOlderOne()
    {
        var client = _factory.CreateBrowserClient();
        var account = await EstablishAsync(client, "code-supersede");
        await client.PostAsync("/api/auth/logout", content: null);

        var fresh = _factory.CreateBrowserClient();

        await RequestCodeAsync(fresh, account.EmailAddress);
        var first = _factory.Email.LatestSignInCode(account.EmailAddress);

        _factory.Clock.Advance(TimeSpan.FromSeconds(61));

        await RequestCodeAsync(fresh, account.EmailAddress);
        var second = _factory.Email.LatestSignInCode(account.EmailAddress);

        second.ShouldNotBe(first);

        // The newest code is the one that works — somebody who asked twice
        // because the first message was slow is holding the second.
        (await VerifyCodeAsync(fresh, account.EmailAddress, second))
            .StatusCode.ShouldBe(HttpStatusCode.OK);

        await fresh.PostAsync("/api/auth/logout", content: null);

        // And redeeming it retired everything else outstanding for the address,
        // so the first message is not a working way in left in a mailbox.
        var third = _factory.CreateBrowserClient();

        (await VerifyCodeAsync(third, account.EmailAddress, first))
            .StatusCode.ShouldBe(HttpStatusCode.Unauthorized);
    }

    [Fact]
    public async Task SigningInWithAPasskeyRetiresAnOutstandingCode()
    {
        var client = _factory.CreateBrowserClient();
        var account = await EstablishAsync(client, "code-superseded-by-passkey");
        await client.PostAsync("/api/auth/logout", content: null);

        var fresh = _factory.CreateBrowserClient();
        await RequestCodeAsync(fresh, account.EmailAddress);

        var code = _factory.Email.LatestSignInCode(account.EmailAddress);

        // The reader gave up waiting for the message and used their passkey.
        (await account.SignInAsync()).StatusCode.ShouldBe(HttpStatusCode.OK);

        // The code that arrived a moment later is no longer a way in.
        (await VerifyCodeAsync(fresh, account.EmailAddress, code))
            .StatusCode.ShouldBe(HttpStatusCode.Unauthorized);
    }

    [Theory]
    [InlineData("")]
    [InlineData("12345")]
    [InlineData("1234567")]
    [InlineData("abcdef")]
    [InlineData(null)]
    public async Task ACodeOfTheWrongShapeIsRefusedWithoutDistinction(string? code)
    {
        var client = _factory.CreateBrowserClient();
        var account = await EstablishAsync(client, "code-shape");
        await client.PostAsync("/api/auth/logout", content: null);

        var fresh = _factory.CreateBrowserClient();
        await RequestCodeAsync(fresh, account.EmailAddress);

        var response = await VerifyCodeAsync(fresh, account.EmailAddress, code);

        // The same 401 a wrong six-digit code gets. A 400 here would tell a
        // caller that their input reached the verifier, which is a small step
        // towards mapping how the endpoint behaves.
        response.StatusCode.ShouldBe(HttpStatusCode.Unauthorized);
    }

    [Fact]
    public async Task AMalformedAddressIsRejectedBeforeAnythingElseHappens()
    {
        var client = _factory.CreateBrowserClient();

        var response = await RequestCodeAsync(client, "not-an-address");

        // Loud, because the shape of an address is not a fact about whether an
        // account exists. Everything downstream of this point converges on one
        // answer; this is the last place it is safe to be specific.
        response.StatusCode.ShouldBe(HttpStatusCode.BadRequest);
    }

    [Fact]
    public async Task TheCodeTravelsInExactlyOneMessageAndIsSixDigits()
    {
        // Two properties, both about containment. A code that also appeared in
        // a security notice, or in a second copy of the sign-in message, would
        // be a credential with more chances to be intercepted than the flow
        // accounts for; and a code of some other length would mean the entry
        // field, the client-side check and the server disagree about what a
        // reader is being asked to type.
        //
        // Where the code must *not* appear — the log — is pinned in
        // Sw5e.Email.Tests, against the provider that does the logging.
        var client = _factory.CreateBrowserClient();
        var account = await EstablishAsync(client, "code-containment");
        await client.PostAsync("/api/auth/logout", content: null);

        var fresh = _factory.CreateBrowserClient();
        await RequestCodeAsync(fresh, account.EmailAddress);

        var code = _factory.Email.LatestSignInCode(account.EmailAddress);

        code.Length.ShouldBe(6);
        code.ShouldAllBe(character => char.IsAsciiDigit(character));

        _factory.Email
            .For(account.EmailAddress)
            .Count(message => message.Body.Contains(code, StringComparison.Ordinal))
            .ShouldBe(1);
    }

    private async Task<AccountFlow> EstablishAsync(HttpClient client, string label) =>
        await AccountFlow.For(client, label).EstablishAsync(_factory.Email);

    private static Task<HttpResponseMessage> RequestCodeAsync(HttpClient client, string emailAddress) =>
        client.PostAsJsonAsync("/api/auth/email/code", new { email = emailAddress });

    private static Task<HttpResponseMessage> VerifyCodeAsync(
        HttpClient client, string emailAddress, string? code) =>
        client.PostAsJsonAsync("/api/auth/email/code/verify", new { email = emailAddress, code });

    /// <summary>A code of the right shape that is not the right code.</summary>
    private static string Wrong(string code) =>
        (code[0] == '0' ? '1' : '0') + code[1..];

    private static async Task<string> EnableTwoFactorAsync(HttpClient client)
    {
        var enrol = await client.PostAsync("/api/auth/mfa/totp/enroll", content: null);
        var uri = (await enrol.ReadJsonAsync()).GetProperty("authenticatorUri").GetString()!;

        var code = TimeBasedOneTimePassword.Generate(TimeBasedOneTimePassword.SecretFrom(uri));

        await client.PostAsJsonAsync("/api/auth/mfa/totp/verify", new { code });

        return uri;
    }
}

/// <summary>
/// The per-caller rate limit on asking for a code.
/// </summary>
/// <remarks>
/// Its own class because the limit has to be tightened to a number a test can
/// reach, and the factory setting that does so would throttle every other test
/// in the file.
/// </remarks>
[Collection(AccountTestCollection.Name)]
public sealed class EmailCodeRateLimitTests(PostgresFixture postgres) : IAsyncLifetime
{
    private ThrottledFactory _factory = null!;

    public Task InitializeAsync()
    {
        _factory = new ThrottledFactory(postgres);
        return Task.CompletedTask;
    }

    public async Task DisposeAsync() => await _factory.DisposeAsync();

    [Fact]
    public async Task ACallerWhoAsksTooOftenIsRefused()
    {
        var client = _factory.CreateBrowserClient();

        // Three different addresses, so the per-address budget cannot be what
        // refuses. The limit under test is the per-caller one, and it is the
        // half of the defence that survives an attacker spreading one request
        // each across ten thousand strangers.
        for (var request = 0; request < 2; request++)
        {
            var accepted = await client.PostAsJsonAsync(
                "/api/auth/email/code",
                new { email = AccountFlow.NewAddress("throttled") });

            accepted.StatusCode.ShouldBe(HttpStatusCode.Accepted);
        }

        var refused = await client.PostAsJsonAsync(
            "/api/auth/email/code",
            new { email = AccountFlow.NewAddress("throttled") });

        refused.StatusCode.ShouldBe(HttpStatusCode.TooManyRequests);

        // A refusal that does not say when to come back is one clients hot-loop
        // against.
        refused.Headers.RetryAfter.ShouldNotBeNull();

        // And nothing was sent on the refused request. A limiter that refused
        // the response after doing the work would be no limit on mail at all.
        _factory.Email.Messages.Count(message => message.Kind == AccountMessageKind.SignInCode)
            .ShouldBe(0);
    }

    private sealed class ThrottledFactory(PostgresFixture postgres) : AccountApiFactory(postgres)
    {
        protected override int EmailCodeRequests => 2;
    }
}
