// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sw5e.Infrastructure.Persistence.Moderation;

#nullable disable

namespace Sw5e.Infrastructure.Persistence.Moderation.Migrations
{
    [DbContext(typeof(Sw5eModerationDbContext))]
    [Migration("20260901161143_FlagResolvedByRevision")]
    partial class FlagResolvedByRevision
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("moderation")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sw5e.Infrastructure.Persistence.Moderation.ContentFlagRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Details")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("details")
                        .UseCollation("C");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("reason")
                        .UseCollation("C");

                    b.Property<Guid>("ReporterUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reporter_user_id");

                    b.Property<long?>("ResolvedByRevisionId")
                        .HasColumnType("bigint")
                        .HasColumnName("resolved_by_revision_id");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by_user_id");

                    b.Property<string>("ReviewerNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reviewer_note")
                        .UseCollation("C");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("status")
                        .UseCollation("C");

                    b.Property<string>("TargetKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("target_key")
                        .UseCollation("C");

                    b.Property<string>("TargetKind")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("target_kind")
                        .UseCollation("C");

                    b.Property<string>("TargetName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("target_name")
                        .UseCollation("C");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("target_type")
                        .UseCollation("C");

                    b.HasKey("Id");

                    b.HasIndex("ReporterUserId", "CreatedAt")
                        .HasDatabaseName("ix_content_flag_reporter");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_content_flag_status_created");

                    b.HasIndex("TargetType", "TargetKey")
                        .HasDatabaseName("ix_content_flag_target");

                    b.HasIndex("ReporterUserId", "TargetType", "TargetKey", "Reason")
                        .IsUnique()
                        .HasDatabaseName("ux_content_flag_outstanding_per_reporter")
                        .HasFilter("\"status\" IN ('open', 'accepted')");

                    b.ToTable("content_flag", "moderation");
                });
#pragma warning restore 612, 618
        }
    }
}
